### ISSUE TITLE
Set scrollbars to window

### ISSUE THREAD

**Issue by MaestroJurko** [gdepourtales/ng-cells#33]
Is it possible to set scrollbars to window instead of table? I have a table inside the main content and I scroll the table with window scrollbars (it took some time to develop that).

Any possibility?

**Comment by kayhadrin** [comment]
Could you clarify or give the URL of a live demo of what you have in mind?

AFAIK, maybe what you'd like can be achieve by adding this css rule:

``` css
.ngc.scroll-wrapper.vertical {
  visibility: hidden;
}
```
